/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_atlas_seiszip_BlockCompressor2 */

#ifndef _Included_org_atlas_seiszip_BlockCompressor2
#define _Included_org_atlas_seiszip_BlockCompressor2
#ifdef __cplusplus
extern "C" {
#endif
#undef org_atlas_seiszip_BlockCompressor2_c_verbose1
#define org_atlas_seiszip_BlockCompressor2_c_verbose1 0L
#undef org_atlas_seiszip_BlockCompressor2_c_checkNonZeroCount_AlwaysTrue
#define org_atlas_seiszip_BlockCompressor2_c_checkNonZeroCount_AlwaysTrue 1L
#undef org_atlas_seiszip_BlockCompressor2_c_complainIfNotFreed
#define org_atlas_seiszip_BlockCompressor2_c_complainIfNotFreed 1L
#undef org_atlas_seiszip_BlockCompressor2_CPDF
#define org_atlas_seiszip_BlockCompressor2_CPDF 0.26f
/*
 * Class:     org_atlas_seiszip_BlockCompressor2
 * Method:    blockCompressorAlloc_native
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_atlas_seiszip_BlockCompressor2_blockCompressorAlloc_1native
  (JNIEnv *, jobject);

/*
 * Class:     org_atlas_seiszip_BlockCompressor2
 * Method:    blockCompressorFree_native
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_atlas_seiszip_BlockCompressor2_blockCompressorFree_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_atlas_seiszip_BlockCompressor2
 * Method:    dataEncode_native
 * Signature: (J[FIF[BII)I
 */
JNIEXPORT jint JNICALL Java_org_atlas_seiszip_BlockCompressor2_dataEncode_1native
  (JNIEnv *, jobject, jlong, jfloatArray, jint, jfloat, jbyteArray, jint, jint);

/*
 * Class:     org_atlas_seiszip_BlockCompressor2
 * Method:    dataDecode_native
 * Signature: (J[BI[BII[F)I
 */
JNIEXPORT jint JNICALL Java_org_atlas_seiszip_BlockCompressor2_dataDecode_1native
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jbyteArray, jint, jint, jfloatArray);

/*
 * Class:     org_atlas_seiszip_BlockCompressor2
 * Method:    setManualDelta_native
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_atlas_seiszip_BlockCompressor2_setManualDelta_1native
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     org_atlas_seiszip_BlockCompressor2
 * Method:    unsetManualDelta_native
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_atlas_seiszip_BlockCompressor2_unsetManualDelta_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
