/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_atlas_seiszip_Transformer2 */

#ifndef _Included_org_atlas_seiszip_Transformer2
#define _Included_org_atlas_seiszip_Transformer2
#ifdef __cplusplus
extern "C" {
#endif
#undef org_atlas_seiszip_Transformer2_c_debug1
#define org_atlas_seiszip_Transformer2_c_debug1 0L
#undef org_atlas_seiszip_Transformer2_c_useJavaVector
#define org_atlas_seiszip_Transformer2_c_useJavaVector 0L
#undef org_atlas_seiszip_Transformer2_c_debug2
#define org_atlas_seiszip_Transformer2_c_debug2 0L
#undef org_atlas_seiszip_Transformer2_c_debug3
#define org_atlas_seiszip_Transformer2_c_debug3 0L
#undef org_atlas_seiszip_Transformer2_FILT00
#define org_atlas_seiszip_Transformer2_FILT00 -0.047393613f
#undef org_atlas_seiszip_Transformer2_FILT01
#define org_atlas_seiszip_Transformer2_FILT01 -0.046626043f
#undef org_atlas_seiszip_Transformer2_FILT02
#define org_atlas_seiszip_Transformer2_FILT02 -0.00119694f
#undef org_atlas_seiszip_Transformer2_FILT03
#define org_atlas_seiszip_Transformer2_FILT03 -0.033824638f
#undef org_atlas_seiszip_Transformer2_FILT04
#define org_atlas_seiszip_Transformer2_FILT04 0.028382527f
#undef org_atlas_seiszip_Transformer2_FILT05
#define org_atlas_seiszip_Transformer2_FILT05 -0.016562475f
#undef org_atlas_seiszip_Transformer2_FILT06
#define org_atlas_seiszip_Transformer2_FILT06 0.07613456f
#undef org_atlas_seiszip_Transformer2_FILT07
#define org_atlas_seiszip_Transformer2_FILT07 0.072506666f
#undef org_atlas_seiszip_Transformer2_FILT08
#define org_atlas_seiszip_Transformer2_FILT08 -0.035952143f
#undef org_atlas_seiszip_Transformer2_FILT09
#define org_atlas_seiszip_Transformer2_FILT09 -0.08879133f
#undef org_atlas_seiszip_Transformer2_FILT10
#define org_atlas_seiszip_Transformer2_FILT10 0.13751054f
#undef org_atlas_seiszip_Transformer2_FILT11
#define org_atlas_seiszip_Transformer2_FILT11 0.073185705f
#undef org_atlas_seiszip_Transformer2_FILT12
#define org_atlas_seiszip_Transformer2_FILT12 0.07364673f
#undef org_atlas_seiszip_Transformer2_FILT13
#define org_atlas_seiszip_Transformer2_FILT13 0.14130238f
#undef org_atlas_seiszip_Transformer2_FILT14
#define org_atlas_seiszip_Transformer2_FILT14 -0.096770205f
#undef org_atlas_seiszip_Transformer2_FILT15
#define org_atlas_seiszip_Transformer2_FILT15 -0.042232785f
#undef org_atlas_seiszip_Transformer2_FILT16
#define org_atlas_seiszip_Transformer2_FILT16 0.012027792f
#undef org_atlas_seiszip_Transformer2_FILT17
#define org_atlas_seiszip_Transformer2_FILT17 -0.017511515f
#undef org_atlas_seiszip_Transformer2_FILT18
#define org_atlas_seiszip_Transformer2_FILT18 0.1229921f
#undef org_atlas_seiszip_Transformer2_FILT19
#define org_atlas_seiszip_Transformer2_FILT19 0.22184989f
#undef org_atlas_seiszip_Transformer2_FILT20
#define org_atlas_seiszip_Transformer2_FILT20 -0.24440831f
#undef org_atlas_seiszip_Transformer2_FILT21
#define org_atlas_seiszip_Transformer2_FILT21 -0.15647236f
#undef org_atlas_seiszip_Transformer2_FILT22
#define org_atlas_seiszip_Transformer2_FILT22 0.013860953f
#undef org_atlas_seiszip_Transformer2_FILT23
#define org_atlas_seiszip_Transformer2_FILT23 -0.03452031f
#undef org_atlas_seiszip_Transformer2_FILT24
#define org_atlas_seiszip_Transformer2_FILT24 0.12838034f
#undef org_atlas_seiszip_Transformer2_FILT25
#define org_atlas_seiszip_Transformer2_FILT25 0.15070076f
#undef org_atlas_seiszip_Transformer2_FILT26
#define org_atlas_seiszip_Transformer2_FILT26 -0.08759645f
#undef org_atlas_seiszip_Transformer2_FILT27
#define org_atlas_seiszip_Transformer2_FILT27 -0.033349037f
#undef org_atlas_seiszip_Transformer2_FILT28
#define org_atlas_seiszip_Transformer2_FILT28 -0.02273096f
#undef org_atlas_seiszip_Transformer2_FILT29
#define org_atlas_seiszip_Transformer2_FILT29 -0.08336709f
#undef org_atlas_seiszip_Transformer2_FILT30
#define org_atlas_seiszip_Transformer2_FILT30 0.1533507f
#undef org_atlas_seiszip_Transformer2_FILT31
#define org_atlas_seiszip_Transformer2_FILT31 0.13196528f
#undef org_atlas_seiszip_Transformer2_FILT32
#define org_atlas_seiszip_Transformer2_FILT32 0.22580096f
#undef org_atlas_seiszip_Transformer2_FILT33
#define org_atlas_seiszip_Transformer2_FILT33 0.32441935f
#undef org_atlas_seiszip_Transformer2_FILT34
#define org_atlas_seiszip_Transformer2_FILT34 -0.36810592f
#undef org_atlas_seiszip_Transformer2_FILT35
#define org_atlas_seiszip_Transformer2_FILT35 -0.39882854f
#undef org_atlas_seiszip_Transformer2_FILT36
#define org_atlas_seiszip_Transformer2_FILT36 0.38496315f
#undef org_atlas_seiszip_Transformer2_FILT37
#define org_atlas_seiszip_Transformer2_FILT37 0.3561661f
#undef org_atlas_seiszip_Transformer2_FILT38
#define org_atlas_seiszip_Transformer2_FILT38 -0.342239f
#undef org_atlas_seiszip_Transformer2_FILT39
#define org_atlas_seiszip_Transformer2_FILT39 -0.2462637f
#undef org_atlas_seiszip_Transformer2_FILT40
#define org_atlas_seiszip_Transformer2_FILT40 0.33917743f
#undef org_atlas_seiszip_Transformer2_FILT41
#define org_atlas_seiszip_Transformer2_FILT41 0.43858314f
#undef org_atlas_seiszip_Transformer2_FILT42
#define org_atlas_seiszip_Transformer2_FILT42 -0.32764277f
#undef org_atlas_seiszip_Transformer2_FILT43
#define org_atlas_seiszip_Transformer2_FILT43 -0.13819301f
#undef org_atlas_seiszip_Transformer2_FILT44
#define org_atlas_seiszip_Transformer2_FILT44 -0.12365391f
#undef org_atlas_seiszip_Transformer2_FILT45
#define org_atlas_seiszip_Transformer2_FILT45 -0.31876284f
#undef org_atlas_seiszip_Transformer2_FILT46
#define org_atlas_seiszip_Transformer2_FILT46 0.4325729f
#undef org_atlas_seiszip_Transformer2_FILT47
#define org_atlas_seiszip_Transformer2_FILT47 0.3342731f
#undef org_atlas_seiszip_Transformer2_FILT48
#define org_atlas_seiszip_Transformer2_FILT48 0.3911554f
#undef org_atlas_seiszip_Transformer2_FILT49
#define org_atlas_seiszip_Transformer2_FILT49 0.37391233f
#undef org_atlas_seiszip_Transformer2_FILT50
#define org_atlas_seiszip_Transformer2_FILT50 0.06256388f
#undef org_atlas_seiszip_Transformer2_FILT51
#define org_atlas_seiszip_Transformer2_FILT51 0.39160565f
#undef org_atlas_seiszip_Transformer2_FILT52
#define org_atlas_seiszip_Transformer2_FILT52 -0.41305915f
#undef org_atlas_seiszip_Transformer2_FILT53
#define org_atlas_seiszip_Transformer2_FILT53 -0.08888602f
#undef org_atlas_seiszip_Transformer2_FILT54
#define org_atlas_seiszip_Transformer2_FILT54 -0.37077668f
#undef org_atlas_seiszip_Transformer2_FILT55
#define org_atlas_seiszip_Transformer2_FILT55 -0.4048998f
#undef org_atlas_seiszip_Transformer2_FILT56
#define org_atlas_seiszip_Transformer2_FILT56 0.40100518f
#undef org_atlas_seiszip_Transformer2_FILT57
#define org_atlas_seiszip_Transformer2_FILT57 0.17178836f
#undef org_atlas_seiszip_Transformer2_FILT58
#define org_atlas_seiszip_Transformer2_FILT58 0.45991656f
#undef org_atlas_seiszip_Transformer2_FILT59
#define org_atlas_seiszip_Transformer2_FILT59 0.33414626f
#undef org_atlas_seiszip_Transformer2_FILT60
#define org_atlas_seiszip_Transformer2_FILT60 0.3152994f
#undef org_atlas_seiszip_Transformer2_FILT61
#define org_atlas_seiszip_Transformer2_FILT61 0.46039212f
#undef org_atlas_seiszip_Transformer2_FILT62
#define org_atlas_seiszip_Transformer2_FILT62 0.13931364f
#undef org_atlas_seiszip_Transformer2_FILT63
#define org_atlas_seiszip_Transformer2_FILT63 0.3715165f
/*
 * Class:     org_atlas_seiszip_Transformer2
 * Method:    transformerAlloc_native
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_atlas_seiszip_Transformer2_transformerAlloc_1native
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_atlas_seiszip_Transformer2
 * Method:    transformerFree_native
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_atlas_seiszip_Transformer2_transformerFree_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_atlas_seiszip_Transformer2
 * Method:    lotFwd_native
 * Signature: (J[FIIII)V
 */
JNIEXPORT void JNICALL Java_org_atlas_seiszip_Transformer2_lotFwd_1native
  (JNIEnv *, jobject, jlong, jfloatArray, jint, jint, jint, jint);

/*
 * Class:     org_atlas_seiszip_Transformer2
 * Method:    lotRev_native
 * Signature: (J[FIIII)V
 */
JNIEXPORT void JNICALL Java_org_atlas_seiszip_Transformer2_lotRev_1native
  (JNIEnv *, jobject, jlong, jfloatArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
