/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_atlas_seiszip_HuffCoder2 */

#ifndef _Included_org_atlas_seiszip_HuffCoder2
#define _Included_org_atlas_seiszip_HuffCoder2
#ifdef __cplusplus
extern "C" {
#endif
#undef org_atlas_seiszip_HuffCoder2_expectedHuffTreeChecksum
#define org_atlas_seiszip_HuffCoder2_expectedHuffTreeChecksum 32640LL
#undef org_atlas_seiszip_HuffCoder2_MAXVALUE
#define org_atlas_seiszip_HuffCoder2_MAXVALUE 256L
#undef org_atlas_seiszip_HuffCoder2_MAXVALUEP1
#define org_atlas_seiszip_HuffCoder2_MAXVALUEP1 257L
/*
 * Class:     org_atlas_seiszip_HuffCoder2
 * Method:    huffCoderAlloc_native
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_atlas_seiszip_HuffCoder2_huffCoderAlloc_1native__
  (JNIEnv *, jobject);

/*
 * Class:     org_atlas_seiszip_HuffCoder2
 * Method:    huffCoderAlloc_native
 * Signature: ([I)J
 */
JNIEXPORT jlong JNICALL Java_org_atlas_seiszip_HuffCoder2_huffCoderAlloc_1native___3I
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     org_atlas_seiszip_HuffCoder2
 * Method:    huffCoderFree_native
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_atlas_seiszip_HuffCoder2_huffCoderFree_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_atlas_seiszip_HuffCoder2
 * Method:    huffEncode_native
 * Signature: (J[BI[BII)I
 */
JNIEXPORT jint JNICALL Java_org_atlas_seiszip_HuffCoder2_huffEncode_1native__J_3BI_3BII
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jbyteArray, jint, jint);

/*
 * Class:     org_atlas_seiszip_HuffCoder2
 * Method:    huffEncode_native
 * Signature: (J[II[BII)I
 */
JNIEXPORT jint JNICALL Java_org_atlas_seiszip_HuffCoder2_huffEncode_1native__J_3II_3BII
  (JNIEnv *, jobject, jlong, jintArray, jint, jbyteArray, jint, jint);

/*
 * Class:     org_atlas_seiszip_HuffCoder2
 * Method:    huffDecode_native
 * Signature: (J[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_org_atlas_seiszip_HuffCoder2_huffDecode_1native
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
