/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_atlas_seiszip_HuffCoder2_HuffNode */

#ifndef _Included_org_atlas_seiszip_HuffCoder2_HuffNode
#define _Included_org_atlas_seiszip_HuffCoder2_HuffNode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
