/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_atlas_seiszip_Transformer2_Policy */

#ifndef _Included_org_atlas_seiszip_Transformer2_Policy
#define _Included_org_atlas_seiszip_Transformer2_Policy
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
